FROM python:3.8-slim

# Maintainer info
LABEL maintainer="info@molecare.co.uk"

# Make working directories
RUN mkdir -p /molecare-ml-api
WORKDIR ./molecare-ml-api

# Copy every file in the source folder to the created working directory
COPY . ./

# Install API dependencies
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils \
    && apt-get -y install curl \
    && apt-get install libgomp1
RUN pip install --no-cache-dir pipenv
#RUN pipenv install --deploy --ignore-pipfile --system
RUN python3 -m venv .venv
RUN pipenv sync

# Start app
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "300", "wsgi"]
