model_config_list: {
  config: {
    name: "model_MobileNet_acc_0.99",
    base_path: "/cnn-models/model_MobileNet_acc_0.99.h5",
    model_platform: "tensorflow",
    model_version_policy: {all: {}}
  }
}